# -*- encoding: utf-8 -*-
{
    'name': 'Open e-Obs Lister Configuration',
    'version': '0.1',
    'category': 'Clinical',
    'license': 'AGPL-3',
    'summary': '',
    'description': """    """,
    'author': 'Neova Health',
    'website': 'http://www.neovahealth.co.uk/',
    'depends': ['nh_eobs_mobile'],
    'data': ['security/ir.model.access.csv',
             'lister_master_data.xml',
             'nh_clinical_lister_view.xml'],
    'qweb': ['static/src/xml/nh_clinical_lister.xml'],
    'css': ['static/src/css/nh_clinical_lister.css'],
    'application': True,
    'installable': True,
    'active': False,
}