# -*- encoding: utf-8 -*-
{
    'name': 'T4 Clinical BHFT Configuration',
    'version': '0.1',
    'category': 'Clinical',
    'license': 'AGPL-3',
    'summary': '',
    'description': """    """,
    'author': 'Tactix4',
    'website': 'http://www.tactix4.com/',
    'depends': ['t4clinical_ui'],
    'data': ['bhft_devices.xml',
             'bhft_pos.xml',
             'bhft_locations.xml',
             'bhft_params.xml',
             'bhft_users.xml',
             'trust.xml'],
    'qweb': ['static/src/xml/t4clinical_bhft.xml'],
    'application': True,
    'installable': True,
    'active': False,
}